//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package euler;

public class ProjectEuler2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int x = 0;
		int y = 1;
		int z = x + y;
		int sume = 0;
		while(z < 4000000){
		    x = y;
		    y = z;
		    z = x + y;
		    if(z % 2 == 0){
		        sume += z; 		    }
		}
		System.out.print(sume);
}
}
